# Generated by Django 4.2.2 on 2023-06-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='product_image',
        ),
    ]
