# Generated by Django 4.2.2 on 2023-07-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('PUNJAB', 'PUNJAB'), ('SINDH', 'SINDH'), ('BALOCHISTAN', 'BALOCHISTAN'), ('KPK', 'KHAIBAR PAKHTOONKHAWA'), ('GILGIT BALTISTAN', 'GILGIT BALTISTAN'), ('AZAD KASHMIR', 'AZAD KASHMIR')], max_length=50),
        ),
    ]
